name: 0.0.$(Date:yyMM.d)$(Rev:rrr)

variables:
  - template: variables/windows.yml

trigger: none
pr: none

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: windows-latest
      os: windows
    sdl:
      credscan:
          suppressionsFile: $(Build.SourcesDirectory)\.ado\config\CredScanSuppressions.json
      spotBugs:
          enabled: false
      prefast:
          enabled: false
    stages:
    - stage: RNWPublish
      jobs:
        # Set version variables and update build number
        - job: SetVersionVars
          displayName: Set Version Variables
          timeoutInMinutes: 15
          steps:
          - template: .ado/templates/checkout-shallow.yml@self

          - template: .ado/templates/set-version-vars.yml@self
            parameters:
              buildEnvironment: Continuous
